Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,10 +34,8 @@ jobs:
       # 第四步：运行Streamlink获取链接，并保存到文件
       # 注意：如果Tonton的网页地址变了，需要修改下面的URL
       - name: Get stream link and save to file
-        run: |
-- name: Get stream link and save to file
-        run: |
-          streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" --http-header "Referer=https://www.tonton.com.my/" --stream-url "https://www.tonton.com.my/live/8tv" best > 8tv.m3u8 || echo "Streamlink failed but the job will not fail."
+     - name: Get stream link and save to file
+        run: streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" --http-header "Referer=https://www.tonton.com.my/" --stream-url "https://www.tonton.com.my/live/8tv" best > 8tv.m3u8 || echo "Streamlink failed but the job will not fail."
 
       # 第五步：自动将生成的文件提交并推送到你的仓库
       - name: Commit and push if changed
